pdf_filename: file.pdf
page: 1
output_filename: file1.csv
to_delete: [
             'Trainee Award Presentation',
             'Coffee Break and Exhibition',
             'Lunch',
             'CoËœee Break and Exhibition',
             'Q&A',
             'Registration'
           ]